### ISSUE TITLE
Link generation for HLS player doesn't work anymore.

### ISSUE THREAD

**Issue by EddyDevProject** [paolodelfino/sc-wrapper#3]
Link generation for HLS player doesn't work anymore. I manually checked source code of streamingcommunity and actually regex of your code doesn't match actually code of SC.
Your regex:
```
new RegExp(
      "window[.]masterPlaylistParams = (.+)let masterPlaylistUrl = new URL[(]'(.+)'[)].+for [(]",
      "s"
    ),
```

But actually code:

 ```
window.masterPlaylist = {
            params: {
                'token': '',
                'token360p': '',
                'token480p': '',
                'token720p': '',
                'token1080p': '',
                'expires': '1704822759',
            },
            url: 'https://vixcloud.at/playlist/TEST'
        }

```

**Comment by paolodelfino** [comment]
Hi, I looked at this error and it's occurring due to a streaming community's problem with the files host. It's not a sc-wrapper's bug. Hopefully, they will fix it soon.

**Comment by EddyDevProject** [comment]
When you checked the site was under maintenance, as written on their telegram channel. If you check now you can check what I wrote to you in the first issue comment
